version: "3.7"
services:

  redis:
    image: redis:alpine
    ports:
            - "5000:5000"
    networks:
      - frontend
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
