version: '2'

services:

  rng:
    build: ./rng

  hasher:
    build: ./hasher

  worker:
    build: ./worker

  coworker:
    build: ./coworker

  web:
    build: .
    ports:
      - 5000:5000

  redis:
    image: redis:alpine

